# Generated by Django 5.0 on 2023-12-24 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(auto_now_add=True)),
                ('clock_in_morning', models.TimeField()),
                ('clock_out_morning', models.TimeField(blank=True, null=True)),
                ('clock_in_afternoon', models.TimeField(blank=True, null=True)),
                ('clock_out_afternoon', models.TimeField(blank=True, null=True)),
                ('is_saturday', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
