# Generated by Django 5.0 on 2023-12-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointrecord',
            name='is_saturday',
        ),
        migrations.AlterField(
            model_name='pointrecord',
            name='clock_in_morning',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
