# Generated by Django 5.0 on 2023-12-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pointrecord_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrecord',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pointrecord',
            name='is_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pointrecord',
            name='is_sunday',
            field=models.BooleanField(default=False),
        ),
    ]
