# Generated by Django 5.0 on 2023-12-27 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pointrecord_is_holiday_pointrecord_is_saturday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointrecord',
            name='register_date',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
