# Generated by Django 5.0 on 2023-12-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_pointrecord_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointrecord',
            name='is_holiday',
            field=models.BooleanField(auto_created=True, default=False),
        ),
        migrations.AlterField(
            model_name='pointrecord',
            name='is_saturday',
            field=models.BooleanField(auto_created=True, default=False),
        ),
        migrations.AlterField(
            model_name='pointrecord',
            name='is_sunday',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
