# Generated by Django 5.0 on 2023-12-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_pointrecord_is_holiday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointrecord',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pointrecord',
            name='is_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pointrecord',
            name='is_sunday',
            field=models.BooleanField(default=False),
        ),
    ]
