# Generated by Django 5.0 on 2023-12-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_pointrecord_is_holiday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrecord',
            name='is_vacation',
            field=models.BooleanField(default=False),
        ),
    ]
