services:
  postgres-timesheet:
    container_name: postgres-timesheet
    image: postgres:16.1-alpine
    ports:
      - "5434:5434"
    volumes:
      - ./data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - PGPORT=5434

  django-timesheet:
    container_name: django-timesheet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8000"
    volumes:
      - ./timesheet:/timesheetd
    env_file:
      - .env
    depends_on:
      - postgres-timesheet