services:
  database:
    container_name: db-timesheet
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    container_name: app-timesheet
    build: .
    ports:
      - "8000:8000"
    volumes:
      - app:/timesheet
    env_file:
      - .env
    depends_on:
      - database

volumes:
  pgdata:
  app: